config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'products#index'

  resources :products do
    resources :reviews, except: [:index, :new, :show]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord

  validates :name, :description, :price, :img_url, presence: true

  validates :price, numericality: { only_integer: true }

  has_many :reviews

end

app/models/review.rb
class Review < ApplicationRecord

  validates :comment, presence: true

  belongs_to :product

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all.order("name")
  end

  def show
    @product = Product.find(params[:id])
    @review = Review.new
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new
    @product.name = params[:product][:name]
    @product.description = params[:product][:description]
    @product.price = params[:product][:price]
    @product.img_url = params[:product][:img_url]

    if @product.save
      flash[:notice] = "Successfully created #{@product.name}"
      redirect_to products_url
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])

    @product.name = params[:product][:name]
    @product.description = params[:product][:description]
    @product.price = params[:product][:price]
    @product.img_url = params[:product][:img_url]

    if @product.save
      flash[:notice] = "Successfully edited #{@product.name}"
      redirect_to products_url
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    flash[:notice] = "Successfully deleted #{@product.name}"
    redirect_to(products_path)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def create
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new
    @review.comment = params[:review][:comment]

    if @review.save
      flash[:notice] = "Successfully submitted comment!"
      redirect_to product_path(@product)
    else
      render 'products/show'
    end
  end

  def edit
    @product = Product.find(params[:product_id])
    @review = @product.reviews.find(params[:id])
  end

  def update
    @review = Review.find(params[:id])

    @review.comment = params[:review][:comment]

    if @review.save
      flash[:notice] = "Successfully edited review!"
      redirect_to product_url(@review.product_id)
    else
      render :edit
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    flash[:notice] = "Successfully deleted comment!"
    redirect_to product_path(params[:product_id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper

  def dollars(amount)
    price_in_dollars = amount.to_f / 100
    sprintf("$%.2f", price_in_dollars)
  end

end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NotAmazon</title>
    <%= csrf_meta_tags %>
    <link type="text/css" rel="stylesheet" href="../../assets/stylesheets/stylesheet.css"/>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <header>
    <div class="flash">
      <% if flash[:notice] %>
        <p class="notice"><%= flash[:notice] %></p>
      <% end %>
    </div>
    <h1>Not Amazon</h1>
    <nav>
      <ul>
        <li><%= link_to "All Products", products_path%></li>
        <li><%= link_to "New Product", new_product_path%></li>
      </ul>
    </nav>
  </header>
  <body>
    <%= yield %>
  </body>
</html>

app/views/products/_products_form.html.erb
<%= form_for product do |f| %>

<div class = "form">
  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.label :price %>
    <%= f.text_field :price %>
  </p>

  <p>
    <%= f.label :img_url %>
    <%= f.text_field :img_url %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

<% if product.errors.any? %>
  <ul>
    <% product.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>
</div>

app/views/products/edit.html.erb
<h1>Editing <%= @product.name %></h1>

<%= render 'products_form', product: @product  %>

app/views/products/index.html.erb
<h1>These are the Products</h1>


<ul>
  <% @products.each do |product| %>
    <div class = "products">
      <li><%= link_to product.name, product_path(product) %></li>
      <li><%= product.description %></li>
      <li><%= dollars(product.price) %></li>
    </div>  
  <% end %>
</ul>

app/views/products/new.html.erb
<h1>New Product</h1>


<%= render 'products_form', product: @product  %>

app/views/products/show.html.erb
<h1><%= @product.name %></h1>


<ul>
  <li>Description: <%= @product.description %></li>
  <li>Price: <%= dollars(@product.price) %></li>
</ul>

<ul>
  <% @product.reviews.each do |review|  %>
    <li><%= review.comment %>
        <%= link_to "Edit", edit_product_review_path(@product, review ) %>
        <%= link_to("Delete", "/products/#{@product.id}/reviews/#{review.id}", method: :delete, data: {confirm: "Are you sure you want to delete this comment?"})  %>
    </li>

  <% end %>
</ul>

<% if @review.errors.any? %>
  <%= @review.errors.full_messages[0] %>
<% end %>

<%= render 'reviews/reviews_forms', product: @product, review: @review %>

<%= link_to "Back", products_path %>
|
<%= link_to "Edit", edit_product_path(@product) %>
|
<%= link_to("Delete", "/products/#{@product.id}", method: :delete, data: {confirm: "Are you sure you want to delete this product?"})  %>

app/views/reviews/_reviews_forms.html.erb
<%= form_for [product, review] do |f|%>
  <p>
    <%= f.label :comment %>
    <%= f.text_area :comment %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/reviews/edit.html.erb
<h1>Edit Comment</h1>

<%= render 'reviews/reviews_forms', product: @product, review: @review %>